<?php

return [
    'slides' => [
        [
            'image' => 'https://images.pexels.com/photos/14977714/pexels-photo-14977714.jpeg?auto=compress&cs=tinysrgb&w=1800&h=900&fit=crop',
            'eyebrow' => 'Navidad en Brevare',
            'title' => 'Regalos que llegan',
            'highlight' => 'con ilusión',
            'subtitle' => 'Encuentra ese detalle especial para compartir esta Navidad.',
            'cta' => 'Descubrir regalos',
            'url' => '/buscar',
            'tone' => 'christmas',
        ],
        [
            'image' => 'https://images.pexels.com/photos/3388335/pexels-photo-3388335.jpeg?auto=compress&cs=tinysrgb&w=1800&h=900&fit=crop',
            'eyebrow' => 'Navidad para tu hogar',
            'title' => 'Momentos para',
            'highlight' => 'celebrar juntos',
            'subtitle' => 'Ideas para vestir tu casa y disfrutar cada encuentro.',
            'cta' => 'Explorar la tienda',
            'url' => '/buscar',
            'tone' => 'home',
        ],
        [
            'image' => 'https://images.pexels.com/photos/14059510/pexels-photo-14059510.jpeg?auto=compress&cs=tinysrgb&w=1800&h=900&fit=crop',
            'eyebrow' => 'Temporada Halloween',
            'title' => 'Un toque de misterio',
            'highlight' => 'y diversión',
            'subtitle' => 'Inspírate con novedades para una temporada diferente.',
            'cta' => 'Ver novedades',
            'url' => '/buscar',
            'tone' => 'halloween',
        ],
        [
            'image' => 'https://images.pexels.com/photos/7989741/pexels-photo-7989741.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900&fit=crop',
            'eyebrow' => 'Tecnología',
            'title' => 'Smartphones y laptops',
            'highlight' => 'hasta -20%',
            'subtitle' => 'Los equipos más nuevos con envío rápido en todo el Perú.',
            'cta' => 'Ver ofertas',
            'url' => '/categoria/tecnologia',
            'tone' => 'default',
        ],
        [
            'image' => 'https://images.pexels.com/photos/34373606/pexels-photo-34373606.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900&fit=crop',
            'eyebrow' => 'Moda',
            'title' => 'Nueva colección',
            'highlight' => 'Moda Mujer',
            'subtitle' => 'Vestidos, blazers y accesorios para esta temporada.',
            'cta' => 'Descubrir',
            'url' => '/categoria/moda/mujer',
            'tone' => 'default',
        ],
        [
            'image' => 'https://images.pexels.com/photos/28609810/pexels-photo-28609810.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900&fit=crop',
            'eyebrow' => 'Hogar',
            'title' => 'Renueva tu descanso',
            'highlight' => 'desde S/ 99',
            'subtitle' => 'Sábanas y acolchados para transformar tu dormitorio.',
            'cta' => 'Ver dormitorio',
            'url' => '/categoria/hogar/dormitorio',
            'tone' => 'default',
        ],
        [
            'image' => 'https://images.pexels.com/photos/16443132/pexels-photo-16443132.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900&fit=crop',
            'eyebrow' => 'Cocina',
            'title' => 'Equipa tu cocina',
            'highlight' => 'hasta -25%',
            'subtitle' => 'Encuentra utensilios y electrodomésticos para tu hogar.',
            'cta' => 'Explorar cocina',
            'url' => '/categoria/hogar/cocina',
            'tone' => 'default',
        ],
    ],
    'texts' => [
        'primary_categories' => 'Compra por categoría',
        'categories' => 'Explora todo',
        'featured' => 'Productos destacados',
        'latest' => 'Lo nuevo',
    ],
    'rotating_phrases' => [
        'Pequeños hallazgos, grandes ideas',
        'Un favorito para descubrir',
        'Inspírate con lo nuevo',
        'Encuentra algo especial',
        'Ideas para regalar y disfrutar',
        'Tu próxima novedad está aquí',
    ],
];
